# Generated by Django 4.2 on 2023-04-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booklet Name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Physics', 'Physics'), ('Movies and comics', 'Movies and comics'), ('Helli copter', 'Helli copter'), ('Biology and Chemistry', 'Biology and Chemistry'), ('Computer', 'Computer'), ('Philosophy', 'Philosophy'), ('Writing', 'Writing')], default='Subject', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('journal_file', models.FileField(blank=True, upload_to='journals/')),
            ],
        ),
        migrations.AddField(
            model_name='booklet',
            name='booklet_file',
            field=models.FileField(blank=True, upload_to='booklets/'),
        ),
        migrations.AlterField(
            model_name='booklet',
            name='category',
            field=models.CharField(choices=[('Math', 'Math'), ('Geometry', 'Geometry'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Literature', 'Literature'), ('Writing', 'Writing'), ('Linguistic', 'Linguistic'), ('GeopGraphy', 'GeopGraphy'), ('English', 'English'), ('Arabic', 'Arabic'), ('Theology', 'Theology'), ('Quran', 'Quran'), ('Social Studies', 'Social Studies'), ('Computer', 'Computer'), ('Social Media Intelligence', 'Social Media Intelligence'), ('Technology', 'Technology')], default='Subject', max_length=50),
        ),
    ]
